"""CLI entry point for the Billing Validation Agent System."""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()


MENU = """
╔══════════════════════════════════════════════════════════╗
║         BILLING VALIDATION AGENT SYSTEM  v1.0           ║
║              Billing-validation prototype                ║
╠══════════════════════════════════════════════════════════╣
║                                                          ║
║  [1]  Run validation  (default data, client_a)           ║
║  [2]  Run validation  (custom input file)                ║
║  [3]  Run validation  (no AI — deterministic mode)       ║
║  [4]  Run validation  (custom client rules)              ║
║  [5]  View last report                                   ║
║  [Q]  Quit                                               ║
║                                                          ║
╚══════════════════════════════════════════════════════════╝
"""


def run_interactive() -> None:
    print(MENU)
    choice = input("Select option: ").strip().upper()

    if choice == "1":
        _run_pipeline("data/input/billing.csv", "client_a", use_ai=True, verbose=True)
    elif choice == "2":
        path = input("Enter billing CSV path: ").strip()
        _run_pipeline(path, "client_a", use_ai=True, verbose=True)
    elif choice == "3":
        _run_pipeline("data/input/billing.csv", "client_a", use_ai=False, verbose=True)
    elif choice == "4":
        client = input("Enter client name (e.g. client_a, client_b): ").strip()
        _run_pipeline("data/input/billing.csv", client, use_ai=True, verbose=True)
    elif choice == "5":
        report = Path("data/output/validation_report.csv")
        if report.exists():
            print(report.read_text())
        else:
            print("No report found. Run a validation first.")
    elif choice == "Q":
        print("Goodbye.")
        sys.exit(0)
    else:
        print("Invalid option.")


def _run_pipeline(billing_input: str, client: str, use_ai: bool, verbose: bool) -> None:
    from orchestrator.orchestrator import Orchestrator
    orch = Orchestrator(verbose=verbose)
    orch.run(billing_input, client=client, use_ai=use_ai)


PROVIDER_KEY_ENV = {
    "anthropic": "ANTHROPIC_API_KEY",
    "openai": "OPENAI_API_KEY",
}


def _api_key_present(provider: str) -> bool:
    """True when the provider's API-key env var is set to a non-empty value."""
    return bool(os.environ.get(PROVIDER_KEY_ENV.get(provider, ""), "").strip())


def _confirm_deterministic_mode(provider: str, assume_yes: bool) -> bool:
    """Prompt the user to confirm a deterministic-mode run when no API key is configured.

    Returns True when the run should proceed (user confirmed, or non-TTY, or --yes).
    Returns False when the user declined and the CLI should exit.
    """
    expected_env = PROVIDER_KEY_ENV.get(provider, "ANTHROPIC_API_KEY")
    other_env = "OPENAI_API_KEY" if expected_env == "ANTHROPIC_API_KEY" else "ANTHROPIC_API_KEY"

    warning = (
        f"\n⚠  No API key found for provider: {provider}\n"
        f"   Expected env var: {expected_env} (or {other_env} for the other provider)\n\n"
        "The pipeline will run in DETERMINISTIC / PROGRAMMATIC / LOCAL mode:\n"
        "  • Discrepancy explanations will be generated by the rule-based\n"
        "    fallback inside AIExplanationAgent — no LLM is called.\n"
        "  • Every output row will carry metadata.generation_mode = \"deterministic\".\n"
        "  • This is a fully supported run mode, but it is not the AI mode.\n\n"
        f"To enable AI: add {expected_env} (or {other_env}) to your .env\n"
        "              file or shell environment, then re-run.\n\n"
        "To suppress this prompt for automated runs, pass --no-ai explicitly\n"
        "(or --yes to accept the deterministic fallback non-interactively).\n"
    )
    print(warning, file=sys.stderr)

    # Non-interactive context (CI, piped input, redirected stdin) → don't hang.
    if assume_yes or not sys.stdin.isatty():
        print(
            "Non-interactive context or --yes set; proceeding in deterministic mode.\n",
            file=sys.stderr,
        )
        return True

    try:
        response = input("Continue in deterministic mode? [y/N]: ").strip().lower()
    except EOFError:
        # No input available — treat like non-TTY.
        return True
    return response in ("y", "yes")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Billing Validation Agent System"
    )
    parser.add_argument(
        "--mode",
        choices=["orchestrated"],
        default="orchestrated",
        help="Execution mode (default: orchestrated)",
    )
    parser.add_argument(
        "--input",
        default="data/input/billing.csv",
        metavar="PATH",
        help="Path to billing CSV (timesheet.csv and contracts.csv auto-discovered in same directory)",
    )
    parser.add_argument(
        "--client",
        default="client_a",
        metavar="NAME",
        help="Client name to load rules from config/client_rules.json (default: client_a)",
    )
    parser.add_argument(
        "--no-ai",
        action="store_true",
        help="Skip AI provider calls; use deterministic explanations",
    )
    parser.add_argument(
        "--ai-provider",
        choices=["anthropic", "openai"],
        default=os.getenv("AI_PROVIDER", "anthropic"),
        help="AI provider for discrepancy explanations (default: AI_PROVIDER or anthropic)",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print step-by-step orchestrator logs and AI explanations",
    )
    parser.add_argument(
        "--interactive",
        action="store_true",
        help="Launch the interactive Delphi-style menu",
    )
    parser.add_argument(
        "--yes",
        action="store_true",
        help=(
            "Accept the deterministic-mode prompt non-interactively. "
            "Use this in CI and other contexts where no human is at the terminal."
        ),
    )

    args = parser.parse_args()

    if args.interactive:
        run_interactive()
        return

    os.environ["AI_PROVIDER"] = args.ai_provider

    # Force a conscious choice: if the user is asking for AI mode (--no-ai not set)
    # but no API key is configured, warn loudly and require confirmation rather than
    # silently downgrading to the deterministic fallback.
    use_ai = not args.no_ai
    if use_ai and not _api_key_present(args.ai_provider):
        if not _confirm_deterministic_mode(args.ai_provider, assume_yes=args.yes):
            print(
                "Aborted. Set the API key and re-run, or pass --no-ai.",
                file=sys.stderr,
            )
            sys.exit(0)
        use_ai = False  # User confirmed the deterministic fallback.

    _run_pipeline(
        billing_input=args.input,
        client=args.client,
        use_ai=use_ai,
        verbose=args.verbose,
    )


if __name__ == "__main__":
    main()
